"""empty message

Revision ID: aef308c933c1
Revises: 96f7bd9a4dfe
Create Date: 2019-04-23 16:42:27.338784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aef308c933c1'
down_revision = '96f7bd9a4dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('answer', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answer', 'question', ['question_id'], ['id'])
    op.create_foreign_key(None, 'answer', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.drop_column('answer', 'question_id')
    op.drop_column('answer', 'author_id')
    # ### end Alembic commands ###
